ДЗ 1
RomadovaIrina/2024-2-VK-EDU-Frontend-I-Romadova pull request #1
Opened 2024-09-19 15:09 UTC by RomadovaIrina

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @rbarannikov.

Что было сделано:
1 Написаны 3 функции
2 Написаны тесты к convertBytesToHuman

2024-09-19 15:40 UTC, RomanBarannickov requested changes

2024-09-19 15:40 UTC, RomanBarannickov commented on convertBytesToHuman.js
> +  }
Не обязательно к исправлению. Просто рекомендация

Поменять местами немного if и else, и тогда от else можно будет вообще отказаться
if (bytes === 0) {return 0} остальной код

2024-09-19 15:40 UTC, RomanBarannickov commented on convertBytesToHuman.js
> +  if (typeof bytes !== 'number' || bytes < 0) {
не хватает проверки на NaN

P.s не забудь и в тестах добавить проверку на Nan, если передать параметром функции

2024-09-19 15:40 UTC, RomanBarannickov commented on convertBytesToHuman.js
> +    const sizeBytes = Math.floor(Math.log(bytes) / Math.log(1024));
А точно нужно Math.log? Кажется и без него получаются порядки

2024-09-19 15:40 UTC, RomanBarannickov commented on convertBytesToHuman.js
> +    }
не обязательно к исправлению
это можно всё представить в виде одной строки
measure = a ? b : c

2024-09-19 15:40 UTC, RomanBarannickov commented on convertBytesToHuman.test.js
> +});
тест на строке 14 уже покрыл это кейс. В параметре функции отрицательное число. Не стоит дублировать

2024-09-19 15:40 UTC, RomanBarannickov commented on convertBytesToHuman.test.js
> +});
В задание сказано: Необходимо покрыть все возможные и невозможные кейсы."
1. строка 13 и строка 15 дублирует кейсы, оставь лучше один из них
2. Из условия покрыто ток отрицательное число и строка, отсутствуют тесты на остальные типы данных в JS. Подумай каких и на всех них добавь тесты

2024-09-19 15:40 UTC, RomanBarannickov commented on correctSentence.js
> +  if (last_sym != ".") {
Не обязательно к исправлению
1. но лучше всегда использовать строгое сравнение, в будущем сэкономит нервы на поиск багов)
2. Опять же просто дополнение. При работе с чистым js, лучше всегда проверять входящий аргумент функции на то что это строка или любой нужный тип данных. Потому что передав сюда не строку, всё сломается

2024-09-19 15:40 UTC, RomanBarannickov commented on nonUniqueElements.js
> +}
Всё ок, опять же не обязательно к исправлению
1. если уж решила сократить код, то можно сразу уже писать return data.filter(...) без res
2. сложность алгоритма сейчас O(n^2). Подумай, как можно было бы его оптимизировать.

2024-09-19 15:40 UTC, RomanBarannickov commented on convertBytesToHuman.js
> +    return `${Number.isInteger(exactSize)? exactSize : exactSize.toFixed(2)} ${measure}`;
Не обязательно к исправлению
лучше всякие вычисление и условия делать до использования их внутри шаблона строк. А внутри шаблона использовать только вычисленные переменные. Это упрощает чтение кода

2024-09-20 08:46 UTC, RomanBarannickov approved these changes
approve
 @martinkomitsky, @HaseProgram, @kgrechin
 @RomadovaIrina респект, что учла рекомендации

2024-09-20 08:46 UTC, RomanBarannickov commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman({name:"test"})).toBe(false);
Не обязательно к исправлению
а массив?) 
ну будем считать что массив - это прототип от объекта)

2024-09-20 08:49 UTC, RomanBarannickov commented on nonUniqueElements.js
> +}
filter - проходит все элементы. О(n)
при каждой итерации используется indexOf и lastIndexOf. Каждая эта функция так же проходиться по всему массиву. 2 * О(n)

получается цикл в цикле, вот и сложность алгоритма O(n^2)

2024-09-21 17:31 UTC, martinkomitsky approved these changes
12!

2024-09-21 17:31 UTC, merged