ДЗ №2
RomadovaIrina/2024-2-VK-EDU-Frontend-I-Romadova pull request #2
Opened 2024-09-24 15:15 UTC by RomadovaIrina

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @rbarannikov.

Что было сделано:
* Деплой страниц
* Стилизация формы отправки сообщений
* Настроена работа с LocalStorage

2024-09-25 21:11 UTC, martinkomitsky commented
> @rbarannikov.

Нужно исправить в шаблоне на правильный ник @RomanBarannickov

2024-09-26 15:27 UTC, RomadovaIrina commented
Подскажите пожалуйста как решить проблему с деплоем. Я "потыкалась", но не особо получилось

![image](https://github.com/user-attachments/assets/a4aaf4be-d8a1-4d69-9bc2-81cc99b91ff8)

2024-09-26 15:34 UTC, RomanBarannickov commented
@RomadovaIrina 
https://github.com/RomadovaIrina/2024-2-VK-EDU-Frontend-I-Romadova/actions/runs/11016721073/job/30594035952?pr=2
тебе необходимо написать конфиг вебпака, чтоб он это дело собрал всё
там в ошибке сказано, что необходимо подключить загрузчик файлов для вебпака

2024-09-27 11:14 UTC, RomadovaIrina commented
> @RomadovaIrina https://github.com/RomadovaIrina/2024-2-VK-EDU-Frontend-I-Romadova/actions/runs/11016721073/job/30594035952?pr=2 тебе необходимо написать конфиг вебпака, чтоб он это дело собрал всё там в ошибке сказано, что необходимо подключить загрузчик файлов для вебпака


Спасибо, вроде починила!

2024-09-27 15:27 UTC, RomanBarannickov requested changes
Потыкал форму. Внешний вид ок. Ток придумай как то дату поменьше сделать и куда то в сторону убрать, а то дата выглядит больше чем сам текст основной. Попробуй просто скопировать внешний вид как в телеге или других мессенджерах. Тип имя где то сверху с лева, дата с права снизу
При клике мышкой на кнопку со стрелкой пропадает фокус с инпута, приходится снова наводиться. Надо пофиксить

2024-09-27 15:27 UTC, RomanBarannickov commented on dist/main.js
> +/*
добавь папку dist в гитигнор
чтоб по 10 раз его не переписывать погугли готовый gitignore для веб разработки, есть уже готовые шаблоны

2024-09-27 15:27 UTC, RomanBarannickov commented on package.json
не совсем понял к чему этот файл относиться, если он относиться к домашке 1, то положи его с домашкой 1
тоже самое актуально и для лок файла

2024-09-27 15:27 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +    <style>
все конечно хорошо, но стили так инлайново мы не пишем внутри html
вынеси все хотя бы в отдельный файлик и подключи так же через веб пак, пусть он за нас делает эту работу

2024-09-27 15:27 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +        <button class="sendButton">
у button может быть type и это поможет с обработкой нажатия кнопки при отправке
https://doka.guide/html/button/

2024-09-27 15:27 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +    <div class="messageBox"></div>
делаем более семантично
контейнер для сообщений -> ui
сообщения -> li

2024-09-27 15:27 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +    <script>
рабочая схема, но так же попрошу вынести в отдельный файлик и собрать уже все в единое через вебпак

2024-09-27 15:27 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +        function loadMessages() {
в современной разработке преимущественно используют стрелочные функции. Перепиши лучше на них
в каком то смысле можно считать function более устаревшим вариантом типа как var со своими нюансами всплытия, которые ведут за собой определенные неудобства при разработке

плюс это заставляет писать код последовательно, как будто бы мы читаем книгу, слева на право, сверху вниз. Сейчас мне чтоб читать МР приходиться прыгать между функциями туда сюда

2024-09-27 15:27 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +            messagesStorage.forEach(function (messageData) {
в целом ок, но я хочу обратить внимание, что данная конструкция очень не оптимальна по производительности
1. каждая вставка appendChild вызывает repaint и reflow. Если сообщений 5 то ок, а если их будет 100500? все будет очень долго работать
2. в данном случае можно сделать вставку только единожды, собрав предварительно всех детей в контейнере и уже их вставив одним разом. 
3. эта статья должна будет помочь https://learn.javascript.ru/modifying-document

2024-09-29 15:37 UTC, RomanBarannickov requested changes
@RomadovaIrina респект за код и правки. Но давай чуть чуть верстку допилим и вообще будет каеф

2024-09-29 15:37 UTC, RomanBarannickov commented on simple-chat/src/index.css
> +    z-index: 100;
выглядит как костыль)
не очень хорошая практика вот так решать проблемы через z-index. Мне кажется это вышло из за проблем с порядком в верстке

2024-09-29 15:37 UTC, RomanBarannickov commented on simple-chat/src/index.css
> +    max-height: calc(100vh - 80px);
если сделаешь -95px = высота футера(85px) + геп(10px) z index не понадобиться в форме

2024-09-29 15:37 UTC, RomanBarannickov commented on simple-chat/src/index.css
> +    margin: 10px 0;
чет посмотрел, не особо марджин и нужен тут, ничего не делает

2024-09-29 15:37 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +</main>
молодец что поправила с прошлого раза, но давай ещё улучшим
в main положим сам чат
а footer - положим form
тогда тебе не понадобиться всякие хаки с position: fixed. Да - это работает, но выглядит не красиво и не совсем правильно
ссылки на семантику
https://doka.guide/html/semantics/
особенно глянь вот эту часть 
https://doka.guide/html/semantics/#kak-semanticheski-razmetit-stranicu

2024-09-29 15:37 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +    }
лучше написать
if (!messageText) {
 return;
}

а дальше полезный код. Так уменьшается вложенность. Меньше вложенность и всякие скобки, выше читабельность

2024-10-05 05:26 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin
 апрув

2024-10-05 05:26 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +<main>
не буду блочить уже это задание
все круто, но у тебя потерялся body
добавь его в следующей домашке
https://doka.guide/html/body/

2024-10-07 19:45 UTC, merged

2024-10-07 19:45 UTC, martinkomitsky commented
12!