Hw3
RomadovaIrina/2024-2-VK-EDU-Frontend-I-Romadova pull request #3
Opened 2024-10-02 21:28 UTC by RomadovaIrina

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @RomanBarannickov .

Что было сделано:
* Начала разбивать на компоненты
* Понять вектор, правильно ли поняла задание
*

2024-10-05 06:23 UTC, RomanBarannickov requested changes
кажется ты забыла сделать новую ветку для hm3 и начала её делать в ветке hm2
пересобери ветку от мастера

2024-10-05 06:40 UTC, RomadovaIrina commented
> кажется ты забыла сделать новую ветку для hm3 и начала её делать в ветке hm2 пересобери ветку от мастера

А почему сейчас так надо? Вроде говорили, если дз предыдущее не сдано, не "замержено" , создавайте ветку от той и делайте так. Я что то неправильно поняла?

2024-10-05 06:44 UTC, RomanBarannickov commented
да точно, забыл, что ещё 2 домашку не слили
сори

2024-10-06 10:12 UTC, RomanBarannickov requested changes
По структуре
1.  все компоненты расположить не в самой папке src
а в папке components
2. стили компонентов, так же разместить рядом с компонентами

По приложению
Такое ощущение делала в какой то спешке и без проверки работоспособности
Баги на ровном месте, которые должны были сразу проявить себя, если бы после правки кода протыкала все функции основные

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/Head/head.js
> +    const head = document.createElement('div');
header
https://doka.guide/html/header/

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/Head/head.js
> +        // menuIcon.addEventListener('click', isChatList);
такое не храним
для таких вещей есть git, чтоб посмотреть, что там было в истории

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/aaa/a.png
аааа?
картинки кладем либо с тем местом где она используется
либо в отдельную папку images и забираем оттуда

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/chatList.html
> +</footer>
забыла body https://doka.guide/html/body/

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/chatList.js
> +// import {FloatingButton} from './FloatButton/floatButton'
удали

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/chatList.js
> +const exampleChats = [
1. вынеси рядом в файлик consts и оттдуа импортни уже этот массив, чтоб он не занимал строки

2. такие вида дефолтные значение и константы обычно помечают специальным начертанием, не помню как правильно называется)
типа вот так лучше _const EXAMPLE_CHATS_

3. мне кажется интерфейсу твоей сущности чат не хватает id по которому потом его можно будет достать и как то с ним манипулировать. Всегда у сущности есть какой то id уникальный, через который с этой сущностью взаимодействуют

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/chatList.js
> +localStorage.setItem('chats', JSON.stringify(exampleChats));
вынеси лучше в отдельную функцию, которая аргументами принимает чаты, и с ними что то там делает, тогда в будущем можно будет легко поменять в одной точке логику и сохранять не в стор, а там на бек кидать запросы

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/chatList.js
> +const chatBox = JSON.parse(localStorage.getItem('chats')) || [];
вынеси в отдельную функцию получение чата и преобразование его

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/chatList.js
> +    localStorage.setItem('chats', JSON.stringify(chatsStorage));
вот снова повторяется эта логика
уже 2 места, в отдельную функцию это

1. что за chatsStorage? Нет такого 
![image](https://github.com/user-attachments/assets/18478e13-e7c1-445f-9e06-171c317cb65c)

2. вообще как будто тут в функции не хватает части логики, получения чата из стора, а потом уже запись


3. писал уже как то, не стоит в добавление чата в одном коде писать и добавление в ui и сторадж. Хотя бы разделить на то, что вынести в отдельную функцию добавление в стор. А лучше сделать две функции, которая одна вставляется в UI, а вторая пишет в стор, и обе они объединены в третьей функции в задачи которой по факту входил объединение двух функций и получение названия нового чата и передачи уже объекта чата в каждую из двух функций

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/chatList.js
> +goBack.addEventListener('click', handleGoback);
да, согласен, что по условию задания этот вариант рабочий, но всё же, я думаю имели ввиду преподаватели, что при клике , пока что,  на любой чат, мы должны попасть на открытую страничку выбранного чата
а не просто использовать кнопку назад, плюс которой совсем нет в макете

2. задание на подумать на будущее, как бы ты реализовывала логику, без history бек и когда надо сделать реальную работу с мульти чатами

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/chatList.js
> +document.querySelector('main').insertBefore(topBar, chatList);
в body вставляй
не в main
семантика такая
<body>
    <header/>
    <main/>
     <footer />

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +
body
https://doka.guide/html/body/

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +document.querySelector('main').insertBefore(topBar, messageBox);
В body вставляй перед main
дока в помощь 
https://learn.javascript.ru/modifying-document

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +    localStorage.setItem('chatMessages', JSON.stringify(messagesStorage));
все тоже самое что и я выше описал к файлу со списком чата

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +        sender: userName,
так же добавлять на каждое сообщение уникальный id

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +    messagesStorage.push(messageData);
вот смотрю на эту штуку и вроде и ок и вроде не нравится, что каким то глобальным объектом постоянно возня идет

мне кажется лучше более явно сделать

написать функцию добавления сообщения в стор
функция принимает аргументом сообщение
внутри уже функция, обращается к функции получения данных и стора
добавляет элемент в массив
снова запихивает данные в сторадж

а то так каждый раз надо держать в голове, что за messagesStorage, откуда взялся, не забыть руками туда положить элемент, чтоб держать синхронизацию с стораджем. Лучше вообще отказаться от этой синхронизации и отдать все на откуп функции добавления сообщения в стор и всё

P.S данный комментарий актуален и для такого же кода с добавлением чата

2024-10-06 10:12 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +    const elemnt_part = makeMessage({sender, text, time});
у тебя тут ошибка
![image](https://github.com/user-attachments/assets/880b2f46-0e7c-4fbb-a086-c3b0ac8d82b3)

1. не надо так в функцию передавать значения, у тебя же уже собран же объект сообщения и причем функция называется создание сообщения. То есть кидай сюда объект  и все. Если ты расширишь объект полями или на оборот сократишь, не надо будет думать про это место

2. все что я выше описал, подтвердилось ошибкой в итоге

2024-10-06 14:14 UTC, RomadovaIrina commented on simple-chat/src/chatList.js
> +goBack.addEventListener('click', handleGoback);
я тут уже запуталась как что куда делать, поэтому пока сделала так

2024-10-08 11:41 UTC, RomanBarannickov approved these changes, later dismissed
@RomadovaIrina апрув, всё хорошо, но обрати внимание на коменты 
@martinkomitsky, @kgrechin

2024-10-08 11:41 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +const chat_ID = urlParams.get('chat_id');
это что за питон закрался в js?)
лучше именовать в camleCase

2024-10-08 11:41 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +const getMessages= (chat_ID) => {
просто id можно назвать аргумент

2024-10-08 11:41 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +        chat_id: parseInt(chat_ID, 10),  // Привязка к текущему чату
в теории я могу открыть сраницу на прямую без query params и значение переменной chat_ID === undefine, или я руками пропишу цифры, что тогда будет?

2024-10-08 11:45 UTC, RomanBarannickov approved these changes, later dismissed

2024-10-11 06:03 UTC, RomanBarannickov approved these changes, later dismissed
@martinkomitsky, @HaseProgram, @kgrechin
 апув

2024-10-11 06:05 UTC, RomanBarannickov submitted a review, later dismissed
апрув
 @martinkomitsky, @HaseProgram, @kgrechin

2024-10-11 14:57 UTC, martinkomitsky approved these changes

2024-10-11 14:57 UTC, martinkomitsky commented
12!

2024-10-11 14:57 UTC, merged