Домашнее задание №5
RomadovaIrina/2024-2-VK-EDU-Frontend-I-Romadova pull request #5
Opened 2024-10-22 15:13 UTC by RomadovaIrina

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @rbarannikov.

Что было сделано:
* Деплой
* Переписано на реакт
* Восстановила стили
* Починила логику работы с чатами

2024-10-23 12:37 UTC, RomanBarannickov requested changes
комментариев вышло много, но ничего ужасного нет, код хорошо написан
продолжай в том же духе
будут трудности или вопросы, сразу приходи

P.s демку после правок не забудь проверить, что всё ок работает

2024-10-23 12:37 UTC, RomanBarannickov commented on .github/workflows/gh-pages.yml
> +        publish_dir: ./react-chat/build
1. vite собирает продакшен сборку в папку dist, а не build из за этого нет ничего на демо стенде
https://romadovairina.github.io/2024-2-VK-EDU-Frontend-I-Romadova/
2. прикрепи ссылку на стенд в описание PR, пожалуйста, чтоб мне не лазить по actions
3. ты можешь либо build -> dist поменять в этом файле, либо в сборщике прописать, что папка куда собирается билд называется build
4. всегда проверяй, что все успешно развернулось на gp физически зайдя на стенд

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
а шрифты не надо подключить которые были ранее?

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +      </div>
есть такое правило, всю логику вычислений по возможности нужно выносить из jsx в переменные и использовать уже только переменные внутри jsx. Т.к сам по себе jsx довольно громоздкий и усложнять его всякой логикой не стоит

даже страницы тоже можно вынести в переменную
типа 
const content = твоё условие as is from jsx
и уже переменную content положить в jsx

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/ChatPlace/ChatPlace.jsx
> +const ChatPlace = ({chatId, avatar, name, lastMessage, time, isRead , onClick}) => {
когда так много пропсов уже набегает, лучше деструктуризацию вынести немного ниже
типа сделать вот так
(props) => {
const {....} = props;
} 
чаще всего это удобней в итоге получается и компонент не выглядит таким огромным и чуть проще читать

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/ChatPlace/ChatPlace.jsx
> +        <img src={avatar || DEFAULT_AVATAR} className='chat-image'/>
выносим логику в переменные, не жаднячаем переменные инициализировать

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/assets/react.svg
а оно надо?

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/HeadBar/HeadBar.jsx
> +const HeadBar = ({ isChatOpen, isChatList, goBackToChatList, userPic, userName = "Unknown" }) => {
в целом ок, но я бы все же предложил бы рассмотреть вариант, что есть какой то общий хедер, который занимается только тем, что блоки внутри себя как то распределяет или вообще отвечает за там ток css и оформление, а наполнение уже создает конкретная страница.

если расположение элементов одинаковое на каждой странице, я бы советовал обратить внимание на то, чтоб хедер просто получал от своего родителя инфу, что где рисовать, а хедер в свою очередь просто бы их вставлял как в "слот"

просто твоё решение тяжело масштабируется
нарушает принципы SOLID на закрытие к изменениям

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/HeadBar/HeadBar.jsx
> +                        <img src={userPic || DEFAULT_AVATAR} className='chat-avatar' alt='avatar' />
В переменную src вынеси

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/HeadBar/HeadBar.jsx
> +            ) : null}
использовать двойные условные операторы - плохая практика
лучше избегать таких вещей

1. в данном случае либо это вообще не понадобиться, если ты все решишь через композицию, как я описал выше
2. если не будешь переделывать. Попробуй решить через if и let переменную
типа  
let content = null

if (comp1) {
content = comp1
}

ну и тп

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/MakeMessage.jsx
> +        <li className={`message ${isLastMessage ? 'message-fly' : ''}`}>
выносим в переменную
плюс я думаю никто не будет ругаться если для стилей подключишь библиотеку https://www.npmjs.com/package/classnames

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +    const chatBox = JSON.parse(localStorage.getItem("chats")) || [];
выносим получение чатов в отдельную функцию
а лучше уже смотреть в стору отдельного апи сервиса, который будет отвечать за это. Потому что уже скоро пойдет полноценное апи с бека и чтоб не переписывать все по 10 раз

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +    localStorage.setItem("chats", JSON.stringify(updatedChats));
в отдельную функцию

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +      <button className="add-chat pulse" onClick={handleAddChat}>
добавь type у button

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +        localStorage.setItem('chatMessages', JSON.stringify(messages));
В отдельную функцию

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +        const allMessages = JSON.parse(localStorage.getItem('chatMessages')) || [];
в отдельную функцию

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +        }
можно заменить на messagesEndRef.current?.scrollIntoView();
https://learn.javascript.ru/optional-chaining

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +            sender: user ? user.name : 'Unknown',
можно ещё вот так
user?.name ?? 'Unknow'
https://learn.javascript.ru/optional-chaining
https://learn.javascript.ru/nullish-operators

у тебя хорошо написано, более явно, просто показываю возможности

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +                        <MakeMessage key={index} sender={sender} text={text} time={time} isLastMessage={message_id === lastMessageId} />
index не очень хорошо использовать как ключ. Если по какой то причине будет пересчет или тип того, бывают случаи, что react не поймет что ему надо перерисовать так как index может не поменяться, а данные поменялись, лучше какой то более специфичный id, типа message id

т.к твои поля и пропсы в компоненты имеют одинаковое название, можно вот так записать
`messages.map(({message_id, ...props},) => (
                        <MakeMessage isLastMessage={message_id === lastMessageId}  {...props}/>`
я не помню как эта штука в реакт называется

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +                    />
в переменную вынеси

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +    const inputFocus = useRef(null);
1. обычно когда работают с ref принято явно прописывать в называние переменной что это ref
inputRef
а фокус или не фокус ты с ним делаешь, уже не важно

2. ref объявила, а привязать его к инпуту - не привязала

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +                    <div ref={messagesEndRef} />
выглядит как хак
а не получиться сделать, привязать ref к контейнеру сообщений, и делать у него scroll просто?

2024-10-23 12:37 UTC, RomanBarannickov commented on react-chat/src/consts/users.js
> +localStorage.setItem('users', JSON.stringify(USERS));
1. не надо так не явно размазывать логику. Хочешь определить сразу пользователей, сделай это в самом грязном компоненте на уровне App.jsx. 
Размазывая так логику, стреляешь себе в ногу, потому что это не явное действие. Каждое действие должно быть максимально явным и понятным, без side effects

2. установку в локалстарж, помсти в функцию и используй функцию уже

2024-10-23 18:25 UTC, RomadovaIrina commented on react-chat/src/assets/react.svg
оно было из демки, я его просто не трогала

2024-10-24 11:01 UTC, RomanBarannickov requested changes
все правку апрув
всё классно, молодец
ждем чтоб сборка собралась и тогда поставлю апрув

2024-10-24 11:01 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +  }
тут ничего править не надо, но замечу
что этот код как таковой не относиться к работе компонента
это больше работа с сущностью и компоненту знать что ты там в локал или не локал кладешь не следует в целом да и не особо ему это интересно в целом)
лучше заведи папочку api
в папке api сделай папку chats
в папке вот в файле опиши этим методы и потому уже эти методы за импортируй в компонент

2024-10-24 11:01 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +    };
тоже самое что и выше я описал

2024-10-24 11:01 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +    const user = getByID(userId)
больше похоже как на работу апи, по этому я бы все же советовал использовать связку useState + useEffect, а то на каждый чих идет запрос user. Будут запросы к серверу, просто скорее всего зависнет браузер от количество запросов

2024-10-24 12:22 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin
апрув

2024-10-27 17:54 UTC, martinkomitsky commented
12!

2024-10-27 17:54 UTC, merged