Домашнее задание №6
RomadovaIrina/2024-2-VK-EDU-Frontend-I-Romadova pull request #6
Opened 2024-10-29 21:05 UTC by RomadovaIrina

# Домашнее задание №6

Прошу @martinkomitsky, @haseprogram, @kgrechin или @RomanBarannickov 

Что было сделано:
* Страница профиля
* Переходы между страницами
* 
![image](https://github.com/user-attachments/assets/44c8ca88-5e27-402d-aa71-d1e7fdfa2d70)

2024-10-30 11:37 UTC, RomanBarannickov requested changes
1. у тебя упала сборка. Предполагаю из из того, что ты установила react router не в тот package json. настоятельно советую удалить package json из root проекта, чтоб таких казусов не происходило
2. да получилось много комментариев, но по большей части они имеют все рекомендательный характер. В остальном код хорошо написан, продолжай в том же духе. Делай по мере возможностей правки комментов. Из главного сейчас это сборку вернуть в строй т.к это условие дз, остальное вторично

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +    localStorage.setItem('users', JSON.stringify(USERS));
в отдельную функцию вынести лучше
типа 
api/user/ и там сделать функцию setUserToLocalStorage типа того

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +    console.log("handleChatClick called with chatId:", chatId, "userId:", userId);
похоже на какой то дебаг

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +          <Route path="/profile/:userId" element={<ProfilePage/>}/>
совет по поводу путей
лучше все пути вынести в словарь
типа того const ROUTES = {root: '/', chat: '/chat'} так легче переиспользовать код и если вдруг надо поменять путь. Это легко сделать. Единая точка входа

для query которые ты используешь в пути, можно так же сделать отдельный словарик, чтоб когда тебе надо по квери этой достать инфу на странице ты использовала переменную одну и туже, а не писала везде руками. Опять же легче поддерживать, в одном месте меняешь и во всем проекте меняется

как вариант, можно написать билдер путей используя паттерн билдер
https://habr.com/ru/companies/otus/articles/552412/

наверное немного не согласен с видом путя для "chat/:chatId/:userId"
кажется излишним параметр userId
как будто бы эту инфу можно было бы вытащить из объекта выбранного чата, id которого у тебя уже собственно есть.

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/api/messages/messages.js
> +    const storedMessages = JSON.parse(localStorage.getItem("chatMessages")) || [];
у тебя функция ниже делает как раз то, что ты тут повторяешь

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/ChatPlace/ChatPlace.jsx
> +                    {isRead && <DoneAllIcon className={styles.readStatus} style={{ color: 'green' }} />}
по возможности не используем стили инлайново
если вдруг не получается поменять стили из за css module нотации и требуется правка глобальных стилей, то стоит изучить доку
и вот вроде статья ещё не плохо поясняет
https://inprod.dev/blog/2020-04-07-global-css-modules/
https://github.com/css-modules/css-modules

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/ChatPlace/ChatPlace.module.scss
> +@use '../../styles/variables' as vars;
не плохое решение, а почему не подошел просто @import?

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/ChatPlace/ChatPlace.module.scss
>  }
изучи документацию scss и возможности вкладывания классов друг в друга для сокращения повторяющегося кода
в данном случае стоило бы записать
.chatPlace {
   &:hover {}
}
& - ссылка на класс внутри которого идет работа
https://sass-lang.com/guide/

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/EditInput/EditInput.jsx
> +        <label className={styles.label}>{labelName}</label>
немножко не хватает семантики и связи между label и инпут
https://doka.guide/html/label/

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/EditInput/EditInput.jsx
> +          onChange={e => onChange(e.target.value)}
и всё таки я советовал бы всегда выносить функции из jsx по возможности

даже в таких простых местах

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +    const foundChat = chats.find(chat => chat.chatId === chatID);
в отдельную функцию лучше вынести поиск чата по id

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +    navigate(`/chat/${chatID}/${foundChat.userId}`);
я как раз описывал выше
1. /chats - в теории может поменяться, лучше использовать переменную
2. можно попробовать написать класс билдер, который возьмет на себе выстраивание путей, чтоб свести к минимуму возможную описку. А такие вещи тяжелее всего обычно найти)

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +            <Link key={chat.chatId} to={`/chat/${chat.chatId}/${chat.userId}`}>
to - тоже лучше вынести в функцию create какую нибудь перед  return
чтоб потом по jsx не лазить не искать.

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +          <button type="button" className={`${styles.addChat} ${styles.pulse}`} onClick={handleAddChat}>
classNames?

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.module.scss
>  }
используем scss

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.module.scss
> +.goBack {
scss

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +  const { chatId, userId } = useParams();
помнишь я выше писал про то, чтобы вынести параметры так же в какой нибудь словарь. Это понадобиться больше, когда появится TS
потому что в TS сигнатура типов у useParams. Всегда будет типа any или Record<string, string | null> чет типа того. И тогда можно будет передать словарь ему в типы и будет красиво выводиться и не ругаться, что chatId, userId имеют типа any

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +  }, [chatId]);
1. вот я как раз писал про это в целом эту логику можно объединить и вытаскивать по объекту чата, инфу по пользователю, кажется избыточным прокидывать ещё и id пользователя. Лишнее раскрытие внутреннего устройства

2. я бы добавил некоторые проверки - так называемые гварды
Проверку на то, что id чата действительно существует и есть такой чат. Потому что в теории я могу просто пойти в url и нафигачить там любую абрукадабру. И тип если такого чата не существует то выкидывать на главную страницу. На список чатов, типа того надо сделать.

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +      sender: user?.name ?? 'Вы',
всё таки я бы тут доработал
в поле sender я бы хранил id на самого себя, чтоб можно было по id вытащить инфу нужную
либо вообще отказаться от поля sender и пересмотреть его на userNameSender и userNamerecipient

зависит от того, как информация будет храниться
просто наш профиль в целом это частный случай пользователя

я бы все таки делил на contacts и profile, так более явно видно разделение отношений на уровне кода.

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +          <ArrowBackIcon className={styles.arrow} sx={{ fontSize: 40 }} onClick={() => navigate('/')} />
onClick в отдельную функцию
/ - вынести в словарь

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +            <span className={styles.messenger}>{user?.name ?? 'Unknown'}</span>
в переменную userName вынести лучше

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +            onChange={(e) => setInputValue(e.target.value)}
в отдельную функцию

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ProfilePage/ProfilePage.module.scss
> +  }
зачем такая вложенность чет не понял немного

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ProfilePage/ProfilePage.jsx
> +            onClick={() => navigate('/')} />
в отдельную функцию

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ProfilePage/ProfilePage.jsx
> +            <span className={styles.messenger}>{!isEditing ? user?.name : 'Edit the profile'}</span>
вычисления в переменную

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ProfilePage/ProfilePage.jsx
> +            <img src={user?.avatar || DEFAULT_AVATAR} className={styles.avatar} alt="avatar" />
вычисления в переменнуб

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ProfilePage/ProfilePage.jsx
> +            <EditIcon onClick={handleEdit} style={{ cursor: 'pointer' }} />
стили в стили выносим

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ProfilePage/ProfilePage.jsx
> +            onChange={value => handleChange('description', value)}
можно сделать функцию обертку на основе замыкания чтоб прокидывать туда имя поля
типа вот так
(fieldName: string) => (value: string) => {handeChange(fieldName, value)}

2024-10-30 11:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ProfilePage/ProfilePage.jsx
> +  const [tempUser, setTempUser] = useState({});
1. назови как то получше, а то не понятно что за поле и для чего оно надо
2. для начального значения либо null. Либо поля формы с какими то дефольными значениями. Потому что рано или поздно они появятся. Типа name: пользователь и тп

2024-11-01 12:47 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin
 апрув
 @RomadovaIrina всё круто. Ещё пару комментов, но там ничего критичного

2024-11-01 12:47 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +const ROUTES = {
лучше вынести в какую нибудь папку consts и оттуда импортировать во все места где используется пути

2024-11-01 12:47 UTC, RomanBarannickov commented on react-chat/src/components/EditInput/EditInput.jsx
> +        />
по семантики label с input связываются через for
https://doka.guide/html/label/

2024-11-01 12:47 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +      navigate(`/profile/${userId}`);
Уже писал
выносишь свой список путей и везде его используешь
Руками нигде не надо писать хардкодом пути
они хардкодом должны быть записаны только в одном месте, и это место сам список ROUTS

2024-11-01 12:47 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +      navigate('/');
лучше обратную проверку
if (!foundChat) {
navigate(ROUTES.root)
return
}
так будет меньше вложенность

ну и второе. Никаких прямых указаний путей. Всё через словарь путей

2024-11-05 07:49 UTC, merged

2024-11-05 07:49 UTC, martinkomitsky commented
12!