Домашнее задание № 7
RomadovaIrina/2024-2-VK-EDU-Frontend-I-Romadova pull request #7
Opened 2024-11-03 13:17 UTC by RomadovaIrina

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @RomanBarannickov .

Что было сделано:
* Начала переход к работе с бэком
*
*

2024-11-14 16:38 UTC, kgrechin commented
@RomanBarannickov

2024-11-14 16:40 UTC, kgrechin commented
@RomadovaIrina, ментора в assignes

2024-11-16 07:37 UTC, RomanBarannickov requested changes
1. запросы летят не к беку на стенде
![image](https://github.com/user-attachments/assets/f93a6168-289f-4d10-8993-634e816aac10)
2. не выполнено условие дз по реализации long pulling или ws Для странницы чатов
3. По поводу всех сераисов апи. User, auth, messsage и тп. Все которые лежат в папке apiService.

- сам class apiService можно вынести в папку config и там оставить
- файлы которые реализую непосредственно запросы. Лучше так и было осатвить в папке апи
- Во всех апи сервисах сущностей одна и таже проблема. В них есть сайд эффекты, которые не должны быть в сервисах запросов. Сервисы запросов должны только отправлять данные, получаться данные, обрабатывать ошибки, делать сериализацию и десерализацию данных между фронтом и беком. Если структуры данных сильно отличаются. Различная предподготовка данных. Обработка данных. Сохранение токенов в ls и все остальное. Это надо вынести из апи сервисом. Сделать папку service и для каждой сущности написать отдельный сервис. Который будет уже заниматься обработкой данных и передачи только готового объекта в сервис апи. Представляй сервис апи как логистический центр. Центр отвечает ток за логистику и чтоб товар был доставлен и отправлен и дошел конечным получателям. Но он не делает упаковку товара. Не сообщает потребителям, что их товар собран. Только логистика и ничего более

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/apiService/apiService.js
> +        this.instance.interceptors.request.use((config) => {
всё тут верно использовала

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/package.json
для скриптов dev и build надо добавить режимы. Чтоб env файлы подтягивались https://vitejs.ru/guide/env-and-mode.html

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +const TempAuth = ({ isRegistering, onRegister, toggleRegister }) => {
1. не стоит писать несколько компонентов в одном файле. Один компонент на один файл
2. название как то плохо описывает. Что за сущность такая и что делает

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/App.jsx
>  const ROUTES = {
вынеси этот словарь в отдельный файл и используй во всем проекте. А не только локально в одном файле

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +      <TempLogin onLogin={handleLogin} />
сделай отдельные просто страницы логина и авторизации. Незачем это запихивать в один компонент

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/apiService/auth/auth.js
> +};
кажется, что эта функция не имеет смысла. Т.к вся логика с токеном авторизации, лежит в api service

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/apiService/chats/chats.js
> +const getChats = async (search = '', pageNum = 1, pageSize = 10) => {
лучше передавать все эти аргументы не по отдельности. А объектом. Так легче будет расширять и поддерживать функцию.

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/apiService/chats/chats.js
> +  const headers = getAuthHeaders();
не делаем так. У тебя для этого токен в api service лежит и сам подставляет через интерсепорты(перехватчики)

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/apiService/auth/auth.js
> +      setTokens({ accessToken: access, refreshToken: refresh });
нужно не только в локалсторадж положить. Но и в инстанс твоего класса apiService Тоже

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/apiService/chats/chats.js
> +  console.log("Fetching chat with ID:", chatId);
такое оставляем ток для локальной разработки. В прод такое не должно ехать

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/apiService/messages/messages.js
> +        page: 1
лучше так же передавать эти параметры. Это не константные величины же

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/AuthGuard.jsx
> +      const refToken = localStorage.getItem('refreshToken');
так у тебя же этим вроде токен сервис занимается

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/AuthGuard.jsx
> +          navigate('/auth');
не пишем сами пути. Пути берем из словаря путей

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/AuthGuard.jsx
> +          localStorage.removeItem('refreshToken');
токен сервис этим занимается

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/AuthGuard.jsx
> +  const [isLoggedIn, setIsLoggedIn] = useState(false);
лучше использовать не флаги как состояния, а какой набор конечных состояний. Типа init | loading | success | error | idle и тп. Так легче управлять состояниями

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/AuthGuard.jsx
> +        navigate('/auth');
тоже самое. Через словарь путей ROUTES.auth

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/TempRegister.jsx
> +    const [avatar, setAvatar] = useState(null);
можно использовать один стейт в котором лежит объект и менять его. Так скорее всего будет даже проще. Легче управлять одним состоянием. Чем всеми сразу

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/TempRegister.jsx
> +      console.log('Отправляемые данные:', formData);
убираем

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/TempRegister.jsx
> +          onChange={(e) => setUsername(e.target.value)}
все on Change выносим из jsx

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +    navigate(`/profile`);
словарь путей

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +      navigate(`/chat/${chatId}`);
в словарь путей

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +  const UserSearch = () => {
выносим в отдельный файл

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +          </li>
все вычисления выносим из jsx

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
>    const createLink = (chatId) => `/chat/${chatId}`;
словарь путей

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +      )}
в отдельный компонент рядом выносим
вычисления выносим из jsx

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +  const [isLoadingUsers, setIsLoadingUsers] = useState(false);
уже очень много становится состояний для одного компонента. Раскидываем через композицию компонентов и кастомные хуки. Такую массу стейтов уже тяжело воспринимать

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +      const loggedUser = await getCurrentUser();
эту штуку наверное стоит запрашивать вообще где то очень высоко на уровне App и прокидывать через context. Эта информация может много где понадобиться и каждый раз при заходе в чат нет смысла запрашивать эту инфу. Можно запросить раз и использовать

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +        navigate('/');
словарь путей

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +      if (foundChat) {
обратная проверка
если нет чата. То просто return из функции и всё. Или куда то вообще из чата выкинуть его

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +          (member) => member.username !== loggedUser.username
мы не ищем сущности по их имени. Для этого используем id. Id - не меняет. А userName и всякие такие вещи с большей вероятностью могут поменять и не совпадать по какой то причине. А id не могут

2024-11-16 07:37 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
не увидел реализацию long pulling или ws. Это условие дз

2024-11-21 08:01 UTC, RomanBarannickov approved these changes, later dismissed
@martinkomitsky, @HaseProgram, @kgrechin
 апрув

@RomadovaIrina Ты молодец. Хорошо поработала. Классно учла рекомендации по разносу апи и сервисов и стало гораздо чище и приятнее. Но без доработок не обошлось

1. слишком частые запросы к беку по обновлению чатов. Чаще чем раз в 15-20 секунд не имеет смысла.
2. При первом логине не подставляется токен авторизации в запрос и происходит дудос пользователя уведомлениями, что чаты не были загружены.
3. Если запрос упал, не надо продолжать опрашивать сервер. Либо опрашивать, но не выводить сообщения в алерт, потому что я даже девтулзы посмотреть толком не могу.
4. не правильное поле отправляется в методе /auth/refresh. Там поле просто называется refresh
https://vkedu-fullstack-div2.ru/api/schema/swagger/#/auth/auth_refresh_create
5. пропала страница регистрации. Смой зайти только через url. А кнопки нет
6. на страницы сообщений слишком часто идем опрос сервера. Так же не чаше чем в 10-15 секунд стоит опрашивать. Если собеседник ответит быстро, то разница во времени не велика. Если собеседник отвечает долго, чаше опрашивать нет смысла
7. добавить отступов сверху и снизу внутри карточки, а то как то все прилипше смотрится 
![image](https://github.com/user-attachments/assets/ee8111a2-780e-4508-b679-e399471fcada)
8. в модальном окне выбора пользователя для чата. Добавить через css отображение выбранного пользователя
9. в модальном окне добавить обводку или смену БГ при ховере на кнопку подтверждения и на кнопку закрытия

2024-11-21 08:01 UTC, RomanBarannickov commented on react-chat/src/apiService/auth/auth.js
> +};
почему два одинаковых метода, да ещё и используется старый, который не работает?

2024-11-21 08:01 UTC, RomanBarannickov commented on react-chat/src/apiService/tokens/tokenManager.js
> +      const response = await apiService.post('auth/refresh/', { refresh: refreshToken });
третий метод рефреша уже. Оставь один только

2024-11-21 08:01 UTC, RomanBarannickov commented on react-chat/src/components/hooks/ChatlistHooks.jsx
> +      }, []);
можно сразу сделать внутри useEffect без использования ref

2024-11-21 08:01 UTC, RomanBarannickov commented on react-chat/src/components/pages/AuthPage/AuthPage.jsx
> +const AuthPage = ({ isRegistering }) => {
сделай два компонента. две разных страницы
страницу регистрации и страницу логина

зачем их объединять то?
у них вообще нет ничего общего

2024-11-21 08:01 UTC, RomanBarannickov commented on react-chat/src/components/pages/AuthPage/LoginForm.jsx
> +        onChange={(e) => setUsername(e.target.value)}
лучше выносить из jsx в отдельные функции

2024-11-21 08:01 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatList/ChatList.jsx
> +      handleAddChat={handleAddChat}
так лучше не делать. Когда так много свойств явно что, что то не так
1. запрашивать список пользователей, можно прям внутри модалки. Эта инфа не особо требуется странице чатов
2. из п.1 следует. Что почти что все поля относящиеся к users, могут быть закрыты внутри самой модалки.
3. в целом всю логику добавления нового чата. Можно и нужно запереть внутри модалки. Странице не особо что надо знать об этом

и тогда и тебя страница станет ещё чище и не будет огромного количества пропсов. Для пропсов можно оставить ток общие поля управления модалкой. open, onClose и тп. Всё остальное спокойно помещается внутрь модалки

2024-11-21 08:01 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
>    }, [chatId]);
можно без ref

2024-11-21 08:01 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +      const data = response.results;
Вот эту штуку, что приходятся response.results делать. Можно положить внутрь как раз сервиса. Чтоб он уже возвращал более подготовленные данные к работе

2024-11-21 08:01 UTC, RomanBarannickov commented on react-chat/src/service/authService.js
> +    setTokens({ accessToken: access, refreshToken: refresh });
надо добавить ещё сохранение токена в инстанс твоего апи сервиса
apiService.setToken(token)

2024-11-21 08:01 UTC, RomanBarannickov commented on react-chat/src/service/authService.js
> +    setTokens({ accessToken: access, refreshToken: newRefresh });
тоже самое
надо добавить в инстанс сразу ещё токен.

2024-11-21 08:01 UTC, RomanBarannickov commented on react-chat/src/service/chatsService.js
> +    const ans =  await getChatsApi(filters);
ans?

2024-11-24 12:00 UTC, martinkomitsky approved these changes

2024-11-24 12:01 UTC, martinkomitsky commented
12!

2024-11-24 12:01 UTC, merged